export const Header = (theme: any) => ({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  borderBottomWidth: theme.border.width,
  borderBottomStyle: theme.border.style,
  borderBottomColor: theme.border.color.default,
  height: theme.header.height.mobile,
  position: 'fixed',
  top: 0,
  left: 0,
  width: '100%',
  zIndex: 100,
  paddingLeft: theme.spacing.unityToRem(8),
  paddingRight: theme.spacing.unityToRem(8),
  background: theme.colors.headerBackground,
  [`@media (min-width: ${theme.screens.lg})`]: {
    height: theme.header.height.desktop,
  },
});
